server:
  port: 8888
  servlet:
    context-path: /admin

spring:
  profiles:
    active: @env@
  main:
    allow-circular-references: true  # 解决循环依赖问题，官方不推荐
  output:
    ansi:
      enabled: always # 彩色日志，可去掉


